- project:
    templates:
      - check-requirements
      - periodic-stable-jobs-neutron
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - publish-openstack-sphinx-docs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
            required-projects:
              - openstack/neutron

